apiVersion: v1
kind: Service
metadata:
  name: news-portal-service
spec:
  type: NodePort
  selector:
    app: news-portal
    any-key: any-value
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31500

