apiVersion: v1
kind: Service
metadata:
  name: svc-primeiro-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: primeiro-pod-declarativo
  ports:
  - port: 60
    targetPort: 70
    nodePort: 30500
