apiVersion: v1
kind: Service
metadata:
  name: svc-primeiro
spec:
  type: NodePort
  selector:
    app: primeiro-pod-declarativo
  ports:
  - port: 70
    targetPort: 8888
    nodePort: 31000


# REMEMBER: This is a node port service

# its purpose is to expose the primeiro-pod app to the,
# external web