apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    app: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8888
      volumeMounts:
        - mountPath: /app-volumes/first-volume
          name: first-volume
    - name: jenkins-container
      image: jenkins:alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8888
      volumeMounts:
        - mountPath: /app-volumes/first-volume
          name: first-volume
  volumes:
    - name: first-volume
      hostPath: /home/first-volume
      type: DirectoryOrCreate