apiVersion: v1
kind: Pod
metadata:
  name: news-system
  labels:
    app: news-system
spec:
  containers:
  - name: news-system-container
    image: aluracursos/sistema-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef:
          name: news-system-configmap
