apiVersion: v1
kind: Pod
metadata:
  name: news-portal
  labels:
    app: news-portal
    any-key: any-value
spec:
  containers:
  - name: news-portal-container
    image: aluracursos/portal-noticias:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    envFrom: 
      - configMapRef:
          name: news-portal-configmap
