apiVersion: v1
kind: PersistentVolume
metadata:
  name: gce-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  gcePersistendDisk:
    pdName: gce-pv-disk
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standart