apiVersion: v1
kind: Pod
metadata:
  name: db-news
  labels:
    app: db-news
spec:
  containers:
  - name: db-news-container
    image: aluracursos/mysql-db:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
    envFrom:
      - configMapRef:
          name: db-news-configmap
