apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: news-portal-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
        app: news-portal
        any-key: any-value
  template:
    metadata: 
      name: news-portal
      labels:
        app: news-portal
        any-key: any-value
      spec:
        containers:
          - name: news-portal-container
            image: aluracursos/portal-noticias:1
            resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
            ports:
              - containerPort: 8080
            envFrom: 
              - configMapRef:
                  name: news-portal-configmap