apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gce-pvc-v2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: slow
